// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jomxjjlyyxwbbyaavvge.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpvbXhqamx5eXh3YmJ5YWF2dmdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNjE2MjEsImV4cCI6MjA2ODgzNzYyMX0.GgkR61Jih0U_hm-Wn6ZMii40NvqcuZO-4GoZ2aqtiDE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});